version: '3'
services:
  drupal8:
    build: docker/www
    ports: 
      - 7070:80
    restart: always
    environment:
      POSTGRES_HOST: pg_db
  pg_db:
    build: docker/db
    restart: always


