version: '3'
services:
  drupal8:
    image: docker-frontend.artifacts.dbccloud.dk/bibdk-backend-www-develop:latest
    ports:
      - 7070:80
    restart: always
    environment:
      POSTGRES_HOST: pg_db
      NAMESPACE_NAME: develop
    command:
      /bin/bash -c ". /run_dev_start.sh && . /entrypoint.sh"
    depends_on:
      - pg_db
    volumes:
      - ./www:/var/www
  pg_db:
    build: db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]


